# Generated by Django 5.0.7 on 2024-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='marca',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
