# Generated by Django 5.1.1 on 2024-09-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='descricao',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
