# Generated by Django 5.0.7 on 2024-08-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoque_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='data_criacao',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
