# Generated by Django 5.1.1 on 2024-09-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoque_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='nome',
            new_name='produto',
        ),
    ]
