# Generated by Django 5.0.7 on 2024-08-20 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_estoque_data_criacao'),
        ('produto', '0004_produto_marca_produto_quantidade_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_produto', to='produto.produto'),
        ),
    ]
