# Generated by Django 5.0.7 on 2024-08-12 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('inicio_de_contrato', models.CharField(max_length=14)),
                ('vigencia', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Requisicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('contrato', models.CharField(blank=True, default='', max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('inicio_de_contrato', models.DateField(blank=True, null=True)),
                ('vigencia', models.DateField(blank=True, null=True)),
                ('data', models.DateField()),
                ('motivo', models.CharField(blank=True, default='', max_length=450)),
                ('envio', models.CharField(blank=True, default='', max_length=100)),
                ('comercial', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_acesso', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_produto', models.CharField(blank=True, default='', max_length=100)),
                ('carregador', models.CharField(blank=True, default='', max_length=100)),
                ('cabo', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_fatura', models.CharField(blank=True, default='', max_length=100)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('forma_pagamento', models.CharField(blank=True, default='', max_length=100)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_nome', to='requisicao.cliente')),
            ],
        ),
    ]
