# Generated by Django 5.1.1 on 2024-09-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
operations = [
    migrations.AlterField(
        model_name='requisicao',
        name='forma_pagamento',
        field=models.CharField(max_length=255, null=True),
    ),
]