# Generated by Django 5.0.7 on 2024-08-12 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0008_alter_cliente_inicio_de_contrato'),
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_nome', to='acompanhamento.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
