# Generated by Django 5.1.1 on 2024-09-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0002_alter_requisicoes_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='id_equipamentos',
            field=models.TextField(blank=True, default='', max_length=1200),
        ),
    ]
