# Generated by Django 5.0.7 on 2024-08-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0002_alter_requisicoes_nome_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='status',
            field=models.CharField(blank=True, choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente')], max_length=50, null=True),
        ),
    ]
