# Generated by Django 5.0.7 on 2024-08-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0003_requisicoes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='TP',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('30', '30'), ('60', '60'), ('360', '360'), ('720', '720')], max_length=50, null=True),
        ),
    ]
