# Generated by Django 5.1.1 on 2024-09-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0003_alter_requisicoes_id_equipamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
