# Generated by Django 5.0.7 on 2024-08-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_produto_valorc_alter_produto_descricao_and_more'),
        ('requisicao', '0004_requisicoes_tp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_PRODUTO', to='produto.produto'),
        ),
    ]
