# Generated by Django 5.0.7 on 2024-08-14 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_produto_valorc_alter_produto_descricao_and_more'),
        ('requisicao', '0005_alter_requisicoes_tipo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='TP',
            field=models.CharField(blank=True, choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_produto', to='produto.produto'),
        ),
    ]
