# Generated by Django 5.0.7 on 2024-09-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0005_alter_requisicoes_motivo_estoque_antenista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque_antenista',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estoque_antenista',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estoque_antenista',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estoque_antenista',
            name='tipo_produto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='estoque_antenista',
            unique_together={('nome', 'tipo_produto')},
        ),
    ]
