# Generated by Django 5.0.7 on 2024-09-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0005_alter_clientes_cnpj'),
        ('produto', '0003_remove_produto_descricao_remove_produto_preco_and_more'),
        ('requisicao', '0006_alter_estoque_antenista_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque_antenista',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estoque_antenista',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenista_nome', to='acompanhamento.clientes'),
        ),
        migrations.AlterField(
            model_name='estoque_antenista',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estoque_antenista',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenista_produto', to='produto.produto'),
        ),
    ]
