# Generated by Django 5.0.7 on 2024-09-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0007_alter_estoque_antenista_endereco_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoque_antenista',
            unique_together=set(),
        ),
    ]
