# Generated by Django 5.0.7 on 2024-09-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0005_alter_clientes_cnpj'),
        ('produto', '0003_remove_produto_descricao_remove_produto_preco_and_more'),
        ('requisicao', '0008_alter_estoque_antenista_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoque_antenista',
            unique_together={('nome', 'tipo_produto')},
        ),
    ]
