# Generated by Django 5.0.7 on 2024-09-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0009_alter_estoque_antenista_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoque_antenista',
            unique_together=set(),
        ),
    ]
