# Generated by Django 5.0.7 on 2024-08-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0010_remove_requisicoes_tipo_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='tipo_fatura',
            field=models.CharField(blank=True, choices=[('Com Custo', 'Com Custo'), ('Sem Custo', 'Sem Custo')], max_length=50, null=True),
        ),
    ]
