# Generated by Django 5.0.7 on 2024-08-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0011_alter_requisicoes_tipo_fatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='observacoes',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
