# Generated by Django 5.0.7 on 2024-09-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0005_alter_clientes_cnpj'),
        ('produto', '0003_remove_produto_descricao_remove_produto_preco_and_more'),
        ('requisicao', '0011_alter_estoque_antenista_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicoescrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('contrato', models.CharField(blank=True, choices=[('', ''), ('Descartavel', 'Descartavel'), ('Retornavel', 'Retornavel')], max_length=50, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_de_equipamentos', models.CharField(blank=True, max_length=14, null=True)),
                ('inicio_de_contrato', models.DateField(blank=True, null=True)),
                ('vigencia', models.CharField(blank=True, choices=[('6', '6'), ('12', '12'), ('18', '18'), ('24', '24'), ('30', '30'), ('36', '36'), ('48', '48')], max_length=50, null=True)),
                ('customizacao', models.CharField(blank=True, choices=[('6', '6'), ('12', '12'), ('18', '18'), ('24', '24'), ('30', '30'), ('36', '36'), ('48', '48')], max_length=50, null=True)),
                ('data', models.DateField(auto_now=True)),
                ('tipo_customizacao', models.CharField(blank=True, choices=[('Sem custumização', 'Sem custumização'), ('Caixa de papelão', 'Caixa de papelão'), ('Caixa de papelão (bateria desacoplada)', 'Caixa de papelão (bateria desacoplada)'), ('Caixa de papelão + DF', 'Caixa de papelão + DF'), ('Termo branco', 'Termo branco'), ('Termo branco + D.F ', 'Termo branco + D.F'), ('Termo branco slim ', 'Termo branco slim'), ('Termo branco slim + D.F +EQT  ', 'Termo branco slim + D.F +EQT'), ('Termo cinza slim + D.F +EQT  ', 'Termo cinza slim + D.F +EQT'), ('Termo branco  (isopor) ', 'Termo branco  (isopor)'), ('Termo branco - bateria externa ', 'Termo branco - bateria externa'), ('Termo marrom + imã', 'Termo marrom + imã'), ('Termo cinza', 'Termo cinza'), ('Termo cinza + imã', 'Termo cinza + imã'), ('Termo preto', 'Termo preto'), ('Termo preto + imã', 'Termo preto + imã'), ('Termo brabco |marrim-slim', 'Termo brabco |marrim-slim'), ('Termo marrom slim +D.F + EQT', 'Termo marrom slim +D.F + EQT'), ('Termo marrom', 'Termo marrom'), ('Caixa blindada', 'Caixa blindada'), ('Tênis/ Sapato', 'Tênis/ Sapato'), ('Projetor', 'Projetor'), ('Caixa de som', 'Caixa de som'), ('Luminaria', 'Luminaria'), ('Alexa', 'Alexa'), ('Video Game', 'Video Game'), ('Secador de cabelo', 'Secador de cabelo'), ('Roteador', 'Roteador'), ('Relogio digital', 'Relogio digital')], max_length=50, null=True)),
                ('motivo', models.CharField(blank=True, choices=[('Tipo de Faturamento', 'Tipo de Faturamento'), ('Aquisicão Nova', 'Aquisicão Nova'), ('Manutenção', 'Manutenção'), ('Aditivo', 'Aditivo'), ('Acessorios', 'Acessorios'), ('Extravio', 'Extravio'), ('Texte', 'Texte'), ('Isca Fast', 'Isca Fast'), ('Isca Fast Agente', 'Isca Fast Agente'), ('Antenista', 'Antenista'), ('Reversa', 'Reversa'), ('Isca FAST', 'Isca FAST'), ('Estoque Antenista', 'Estoque Antenista')], default='', max_length=50, null=True)),
                ('envio', models.CharField(blank=True, choices=[('Agente', 'Agente'), ('Retirada', 'Retirada'), ('Motoboy', 'Motoboy'), ('transportadora', 'Transportadora'), ('Correio', 'Correio'), ('Comercial', 'Comercial')], max_length=50, null=True)),
                ('taxa_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comercial', models.CharField(blank=True, default='', max_length=100)),
                ('carregador', models.CharField(blank=True, default='', max_length=100)),
                ('cabo', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_fatura', models.CharField(blank=True, choices=[('Com Custo', 'Com Custo'), ('Sem Custo', 'Sem Custo')], max_length=50, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('forma_pagamento', models.CharField(blank=True, default='', max_length=100)),
                ('observacoes', models.TextField(blank=True, default='', max_length=250)),
                ('status', models.CharField(blank=True, default='Pendente', max_length=50, null=True)),
                ('TP', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('30', '30'), ('60', '60'), ('360', '360'), ('720', '720')], max_length=50, null=True)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_up_nome', to='acompanhamento.clientes')),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_up_produto', to='produto.produto')),
            ],
        ),
    ]
