# Generated by Django 5.0.7 on 2024-09-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0012_requisicoescrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requisicoescrate',
        ),
    ]
