# Generated by Django 5.0.7 on 2024-08-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0012_alter_requisicoes_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente')], default='Pendente', max_length=50),
        ),
    ]
