# Generated by Django 5.1.1 on 2024-09-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0014_alter_estoque_antenista_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='antenista',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
