# Generated by Django 5.0.7 on 2024-08-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0015_alter_requisicoes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='status',
            field=models.CharField(blank=True, choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente'), ('Configurado', 'Configurado'), ('Expedido', 'Expedido')], default='Pendente', max_length=50, null=True),
        ),
    ]
