# Generated by Django 5.1.1 on 2024-09-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0015_requisicoes_antenista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque_antenista',
            name='nome',
            field=models.CharField(choices=[('ALCIDES', 'ALCIDES'), ('EZEQUIEL', 'EZEQUIEL'), ('NILDO', 'NILDO'), ('ALEX', 'ALEX'), ('ANDERSON', 'ANDERSON'), ('ANTONIEQUE', 'ANTONIEQUE'), ('OSNI', 'OSNI'), ('ELTON', 'ELTON'), ('NEY', 'NEY'), ('ANDRÉ', 'ANDRÉ'), ('RILDO', 'RILDO'), ('WELLINGTHON', 'WELLINGTHON'), ('GERSON WALACE', 'GERSON WALACE'), ('JUSTINO', 'JUSTINO'), ('ANTONIO', 'ANTONIO'), ('FRANCISCO', 'FRANCISCO'), ('OSMAN', 'OSMAN'), ('TONHARA', 'TONHARA'), ('EMERSON', 'EMERSON'), ('MARCELO', 'MARCELO'), ('JEFFERSON', 'JEFFERSON'), ('GUILHERME', 'GUILHERME'), ('MARCIO', 'MARCIO'), ('SAMPAIO', 'SAMPAIO'), ('DIOGO', 'DIOGO'), ('WESLEY', 'WESLEY'), ('EVERALDO / SAMUEL', 'EVERALDO / SAMUEL'), ('ERIK', 'ERIK'), ('LUCAS CARVALHO', 'LUCAS CARVALHO'), ('RODRIGO', 'RODRIGO'), ('PITTA', 'PITTA'), ('JUSTO', 'JUSTO'), ('PAULO HENRIQUE', 'PAULO HENRIQUE'), ('EDUARDO', 'EDUARDO'), ('YURI', 'YURI'), ('RAFAEL', 'RAFAEL')], max_length=50),
        ),
    ]
