# Generated by Django 5.0.7 on 2024-08-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0016_alter_requisicoes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='status_faturamento',
            field=models.CharField(blank=True, choices=[('', ''), ('A Faturar', 'A Faturar'), ('Faturado sem Taxa', 'Faturado sem Taxa'), ('Faturado com Taxa', 'Faturado com Taxa'), ('Pendente', 'Pendente'), ('Pendente sem Contrato', 'Pendente sem Contrato'), ('Pendente Sem Termo', 'Pendente Sem Termo'), ('Pendente Sem Contrato', 'Pendente Sem Contrato'), ('Sem Custo', 'Sem Custo'), ('Dados invalidos', 'Dados invalidos')], max_length=50, null=True),
        ),
    ]
