# Generated by Django 5.1.1 on 2024-09-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0017_rename_nome_estoque_antenista_antenista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque_antenista',
            old_name='antenista',
            new_name='nome',
        ),
    ]
