# Generated by Django 5.0.7 on 2024-08-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0018_alter_requisicoes_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Tipo de Faturamento', 'Tipo de Faturamento'), ('Aquisicão Nova', 'Aquisicão Nova'), ('Manutenção', 'Manutenção'), ('Aditivo', 'Aditivo'), ('Acessorios', 'Acessorios'), ('Extravio', 'Extravio'), ('Texte', 'Texte'), ('Isca Fast', 'Isca Fast'), ('Isca Fast Agente', 'Isca Fast Agente'), ('Antenista', 'Antenista'), ('Reversa', 'Reversa')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='status_faturamento',
            field=models.CharField(blank=True, choices=[('', ''), ('A Faturar', 'A Faturar'), ('Faturado sem Taxa', 'Faturado sem Taxa'), ('Faturado com Taxa', 'Faturado com Taxa'), ('Pendente', 'Pendente'), ('Pendente sem Contrato', 'Pendente sem Contrato'), ('Pendente Sem Termo', 'Pendente Sem Termo'), ('Pendente Sem Contrato', 'Pendente Sem Contrato'), ('Sem Custo', 'Sem Custo'), ('Dados invalidos', 'Dados invalidos')], default='Selecione o status do faturamento', max_length=50, null=True),
        ),
    ]
