# Generated by Django 5.0.7 on 2024-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0019_alter_requisicoes_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='status',
            field=models.CharField(blank=True, choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente'), ('Expedição', 'Expedição'), ('Expedido', 'Expedido')], default='Pendente', max_length=50, null=True),
        ),
    ]
