# Generated by Django 5.0.7 on 2024-09-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0020_alter_requisicoes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='id_equipamentos',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
