# Generated by Django 5.1.1 on 2024-09-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0021_alter_requisicoes_customizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='envio',
            field=models.CharField(blank=True, choices=[('Agente', 'Agente'), ('Retirada na base', 'Retirada na base'), ('Motoboy', 'Motoboy'), ('transportadora', 'Transportadora'), ('Correio', 'Correio'), ('Comercial', 'Comercial')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Tipo de Faturamento', 'Tipo de Faturamento'), ('Aquisicão Nova', 'Aquisicão Nova'), ('Manutenção', 'Manutenção'), ('Aditivo', 'Aditivo'), ('Acessórios', 'Acessórios'), ('Extravio', 'Extravio'), ('Teste', 'Teste'), ('Isca Fast', 'Isca Fast'), ('Isca Fast - Agente', 'Isca Fast - Agente'), ('Antenista', 'Antenista'), ('Reversa', 'Reversa'), ('Isca FAST', 'Isca FAST'), ('Estoque Antenista', 'Estoque Antenista')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='status_faturamento',
            field=models.CharField(blank=True, choices=[('', ''), ('A Faturar', 'A Faturar'), ('Faturado sem taxa', 'Faturado sem taxa'), ('Faturado com taxa', 'Faturado com taxa'), ('Pendente', 'Pendente'), ('Pendente sem Contrato', 'Pendente sem Contrato'), ('Pendente Sem Termo', 'Pendente Sem Termo'), ('Pendente Sem Contrato', 'Pendente Sem Contrato'), ('Sem Custo', 'Sem Custo'), ('Dados invalidos', 'Dados invalidos')], default='', max_length=50, null=True),
        ),
    ]
