# Generated by Django 5.0.7 on 2024-09-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0022_alter_requisicoes_vigencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicoes',
            name='id_equipamentos',
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='envio',
            field=models.CharField(blank=True, choices=[('Agente', 'Agente'), ('Retirada', 'Retirada'), ('Motoboy', 'Motoboy'), ('Transportadora', 'Transportadora'), ('Correio', 'Correio'), ('Comercial', 'Comercial')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='vigencia',
            field=models.CharField(blank=True, choices=[('6', '6'), ('12', '12'), ('18', '18'), ('24', '24'), ('36', '36')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipamento', models.TextField(blank=True, default='', max_length=250)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='requisicao.requisicoes')),
            ],
        ),
    ]
