# Generated by Django 5.1.1 on 2024-09-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0022_alter_requisicoes_envio_alter_requisicoes_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
