# Generated by Django 5.1.1 on 2024-09-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0023_alter_requisicoes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='forma_pagamento',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
