# Generated by Django 5.0.7 on 2024-09-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0023_remove_requisicoes_id_equipamentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='id',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='requisicao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='equipamento', serialize=False, to='requisicao.requisicoes'),
        ),
    ]
