# Generated by Django 5.0.7 on 2024-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0024_remove_equipamento_id_alter_equipamento_requisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='id_equipamentos',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='envio',
            field=models.CharField(blank=True, choices=[('Agente', 'Agente'), ('Retirada', 'Retirada'), ('Motoboy', 'Motoboy'), ('transportadora', 'Transportadora'), ('Correio', 'Correio'), ('Comercial', 'Comercial')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='status',
            field=models.CharField(blank=True, choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente'), ('Configurado', 'Configurado'), ('Expedido', 'Expedido')], default='Pendente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
