# Generated by Django 5.1.1 on 2024-09-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0024_alter_requisicoes_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='forma_pagamento',
            field=models.CharField(default='', max_length=100),
        ),
    ]
