# Generated by Django 5.0.7 on 2024-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0025_requisicoes_id_equipamentos_alter_requisicoes_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='status',
            field=models.CharField(blank=True, default='Pendente', max_length=50, null=True),
        ),
    ]
