# Generated by Django 5.0.7 on 2024-09-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0027_requisicoes_taxa_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='customizacao',
            field=models.CharField(blank=True, choices=[('6', '6'), ('12', '12'), ('18', '18'), ('24', '24'), ('30', '30'), ('36', '36'), ('48', '48')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requisicoes',
            name='numero_de_equipamentos',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='requisicoes',
            name='tipo_customizacao',
            field=models.CharField(blank=True, choices=[('Sem custumização', 'Sem custumização'), ('Caixa de papelão', 'Caixa de papelão'), ('Caixa de papelão (bateria desacoplada)', 'Caixa de papelão (bateria desacoplada)'), ('Caixa de papelão + DF', 'Caixa de papelão + DF'), ('Termo branco', 'Termo branco'), ('Termo branco + D.F ', 'Termo branco + D.F'), ('Termo branco slim ', 'Termo branco slim'), ('Termo branco slim + D.F +EQT  ', 'Termo branco slim + D.F +EQT'), ('Termo cinza slim + D.F +EQT  ', 'Termo cinza slim + D.F +EQT'), ('Termo branco  (isopor) ', 'Termo branco  (isopor)'), ('Termo branco - bateria externa ', 'Termo branco - bateria externa'), ('Termo marrom + imã', 'Termo marrom + imã'), ('Termo cinza', 'Termo cinza'), ('Termo cinza + imã', 'Termo cinza + imã'), ('Termo preto', 'Termo preto'), ('Termo preto + imã', 'Termo preto + imã'), ('Termo brabco |marrim-slim', 'Termo brabco |marrim-slim'), ('Termo marrom slim +D.F + EQT', 'Termo marrom slim +D.F + EQT'), ('Termo marrom', 'Termo marrom'), ('Caixa blindada', 'Caixa blindada'), ('Tênis/ Sapato', 'Tênis/ Sapato'), ('Projetor', 'Projetor'), ('Caixa de som', 'Caixa de som'), ('Luminaria', 'Luminaria'), ('Alexa', 'Alexa'), ('Video Game', 'Video Game'), ('Secador de cabelo', 'Secador de cabelo'), ('Roteador', 'Roteador'), ('Relogio digital', 'Relogio digital')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='vigencia',
            field=models.CharField(blank=True, choices=[('6', '6'), ('12', '12'), ('18', '18'), ('24', '24'), ('30', '30'), ('36', '36'), ('48', '48')], max_length=50, null=True),
        ),
    ]
