# Generated by Django 5.1.1 on 2024-09-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T42Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipamento', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Atualizado', 'Atualizado'), ('Configurado', 'Configurado'), ('Não Atualizado', 'Não Atualizado'), ('Não Configurado', 'Não Configurado'), ('Manutenção', 'Manutenção')], max_length=50, null=True)),
            ],
        ),
    ]
