# Generated by Django 5.1.1 on 2024-09-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0003_clientes_corretora_clientes_gr_and_more'),
        ('t42', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t42model',
            name='nome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t42_nome', to='acompanhamento.clientes'),
        ),
    ]
