# Generated by Django 5.1.1 on 2024-09-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t42', '0002_t42model_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t42model',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
