# Generated by Django 5.1.1 on 2024-09-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t42', '0003_alter_t42model_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='t42model',
            name='reversa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
