# Generated by Django 5.1.1 on 2024-09-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t42', '0005_t42model_estoque_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t42model',
            name='estoque_status',
        ),
    ]
