# Generated by Django 5.1.1 on 2024-09-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t42', '0006_remove_t42model_estoque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='t42model',
            name='estoque_status',
            field=models.CharField(blank=True, choices=[('estoque', 'Estoque'), ('retornado', 'Retornado'), ('enviado', 'Enviado'), ('extraviado', 'Extraviado')], max_length=50, null=True),
        ),
    ]
