# Generated by Django 5.1.1 on 2024-09-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t42', '0008_t42model_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t42model',
            name='status',
            field=models.CharField(blank=True, choices=[('Atualizado e Configurado', 'Atualizado e Configurado'), ('Não Atualizado', 'Não Atualizado'), ('Não Configurado', 'Não Configurado'), ('Manutenção', 'Manutenção')], max_length=50, null=True),
        ),
    ]
