# Generated by Django 5.1.1 on 2024-09-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t42', '0009_alter_t42model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='t42model',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
