# Generated by Django 5.1.1 on 2024-09-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t42', '0010_t42model_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t42model',
            name='estoque_status',
            field=models.CharField(blank=True, choices=[('Estoque', 'Estoque'), ('retornado', 'Retornado'), ('enviado', 'Enviado'), ('extraviado', 'Extraviado')], max_length=50, null=True),
        ),
    ]
