# Generated by Django 5.0.7 on 2024-09-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t42', '0016_alter_t42model_estoque_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t42model',
            name='estoque_status',
            field=models.CharField(blank=True, choices=[('Estoque', 'Estoque'), ('Retornando', 'Retornando'), ('Enviado', 'Enviado'), ('Estraviado', 'Estraviado'), ('Manutenção', 'Manutenção')], max_length=50, null=True),
        ),
    ]
