# Generated by Django 5.1.1 on 2024-09-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t42', '0017_alter_t42model_estoque_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t42model',
            name='equipamento',
            field=models.CharField(choices=[('TETS', 'TETS'), ('TETS R', 'TETS R'), ('LOKIES', 'LOKIES')], max_length=100, null=True),
        ),
    ]
