# Generated by Django 5.0.7 on 2024-09-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_produto_marca_produto_quantidade_alter_produto_preco'),
        ('tuper', '0002_formulario_divisao'),
    ]

    operations = [
        migrations.CreateModel(
            name='estoque_tuper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='produto.produto')),
            ],
        ),
    ]
