# Generated by Django 5.0.7 on 2024-08-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0012_rename_quabtidade_clientes_quantidade'),
        ('manutencaolist', '0001_initial'),
        ('produto', '0004_produto_marca_produto_quantidade_alter_produto_preco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='manutencoes',
            new_name='manutensaolis',
        ),
    ]
