# Generated by Django 5.0.7 on 2024-08-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_options_remove_cliente_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='inicio_de_contrato',
            field=models.CharField(default='nome', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='vigencia',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
    ]
