# Generated by Django 5.0.7 on 2024-08-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_termino_alter_cliente_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=50),
        ),
    ]
