# Generated by Django 5.0.7 on 2024-08-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='equipamento',
            field=models.CharField(choices=[('Isaca', 'Isca'), ('Rastreador', 'Rastreador'), ('Tets', 'Tets')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
