# Generated by Django 5.1.1 on 2024-09-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodemanutencao',
            name='quantidade',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
