# Generated by Django 5.0.7 on 2024-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodemanutencao',
            name='manutencaoequipamentos',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='registrodemanutencao',
            name='retornoequipamentos',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='registrodemanutencao',
            name='setor',
            field=models.CharField(blank=True, choices=[('Entrada', 'Entrada'), ('Manutenção', 'Manutenção'), ('configuração', 'configuração')], max_length=50, null=True),
        ),
    ]
