# Generated by Django 5.1.1 on 2024-09-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0002_registrodemanutencao_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retorno',
            name='id_equipamentos',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
