# Generated by Django 5.0.7 on 2024-08-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0002_registrodemanutencao_manutencaoequipamentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodemanutencao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
    ]
