# Generated by Django 5.1.1 on 2024-09-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0003_alter_retorno_id_equipamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodemanutencao',
            name='observacoes',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
