# Generated by Django 5.0.7 on 2024-08-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0004_imagemregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemregistro',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
