# Generated by Django 5.0.7 on 2024-09-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0004_registrodemanutencao_observacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemregistro',
            old_name='descricao',
            new_name='id_equipamento',
        ),
        migrations.RemoveField(
            model_name='imagemregistro',
            name='setorid',
        ),
    ]
