# Generated by Django 5.0.7 on 2024-08-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0005_imagemregistro_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemregistro',
            name='setorid',
            field=models.CharField(blank=True, choices=[('expedicao', 'expedicao'), ('Manutenção', 'Manutenção'), ('configuração', 'configuração')], default='Pendente', max_length=50, null=True),
        ),
    ]
