# Generated by Django 5.1.1 on 2024-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0005_rename_descricao_imagemregistro_id_equipamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='numero_equipamento',
            field=models.TextField(blank=True, default='', max_length=2500),
        ),
    ]
