# Generated by Django 5.0.7 on 2024-08-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0007_remove_registrodemanutencao_tipo_problema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemregistro',
            name='setorid',
            field=models.CharField(blank=True, choices=[('expedicao', 'expedicao'), ('Manutenção', 'Manutenção'), ('configurção', 'configuração')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='status',
            field=models.CharField(blank=True, choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente'), ('Configurado', 'Configurado'), ('expedido', 'expedido')], default='Pendente', max_length=50, null=True),
        ),
    ]
