# Generated by Django 5.0.7 on 2024-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0009_alter_registrodemanutencao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodemanutencao',
            name='arquivo',
        ),
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='faturamento',
            field=models.CharField(blank=True, choices=[('', ''), ('Com_Custo', 'Com Custo'), ('Sem_Custo', 'Sem Custo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='status',
            field=models.CharField(blank=True, default='Pendente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='tipo_customizacao',
            field=models.CharField(blank=True, choices=[('', ''), ('Sem customização', 'Sem customização'), ('Caixa de papelão', 'Caixa de papelão'), ('Caixa de papelão (bateria desacoplada)', 'Caixa de papelão (bateria desacoplada)')], max_length=50, null=True),
        ),
    ]
