# Generated by Django 5.0.7 on 2024-09-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0010_remove_registrodemanutencao_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemregistro',
            name='setorid',
            field=models.CharField(blank=True, choices=[('Retorno', 'Retorno'), ('expedicao', 'expedicao'), ('Manutenção', 'Manutenção'), ('configurção', 'configuração')], default='', max_length=50, null=True),
        ),
    ]
