# Generated by Django 5.0.7 on 2024-09-09 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0012_rename_quabtidade_clientes_quantidade'),
        ('produto', '0004_produto_marca_produto_quantidade_alter_produto_preco'),
        ('registrodemanutencao', '0012_retorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retorno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='acompanhamento.clientes'),
        ),
        migrations.AlterField(
            model_name='retorno',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produto.produto'),
        ),
    ]
