# Generated by Django 5.0.7 on 2024-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0014_rename_descricao_retorno_id_equipamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retorno',
            name='id_equipamentos',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
