# Generated by Django 5.1.1 on 2024-09-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualit',
            name='customizacao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qualit',
            name='observacoes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
