# Generated by Django 5.0.7 on 2024-09-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualit', '0002_qualit_observacoes'),
        ('qualit', '0002_qualit_usuario'),
    ]

    operations = [
    ]
