# Generated by Django 5.1.1 on 2024-09-18 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualit', '0002_qualit_customizacao_alter_qualit_observacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualit',
            name='cliente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualit',
            name='comercial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualit',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualit',
            name='usuario',
            field=models.ForeignKey(default='Quality', on_delete=django.db.models.deletion.CASCADE, related_name='qualit_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
