# Generated by Django 5.0.7 on 2024-09-04 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualit', '0003_merge_0002_qualit_observacoes_0002_qualit_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualit',
            name='usuario',
            field=models.ForeignKey(default=10000000000, on_delete=django.db.models.deletion.CASCADE, related_name='qualit_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
