# Generated by Django 5.1.1 on 2024-09-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualit', '0003_alter_qualit_cliente_alter_qualit_comercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualit',
            name='usuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
