# Generated by Django 5.1.1 on 2024-09-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualit', '0004_alter_qualit_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualit',
            name='data',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
