# Generated by Django 5.0.7 on 2024-08-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
        migrations.DeleteModel(
            name='ExemploModel',
        ),
    ]
