# Generated by Django 5.1.1 on 2024-09-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0002_clientes_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='corretora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='gr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='transportadora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
