# Generated by Django 5.1.1 on 2024-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0003_clientes_corretora_clientes_gr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='nome_fantasia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
