# Generated by Django 5.1.1 on 2024-09-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0004_clientes_nome_fantasia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
    ]
