# Generated by Django 5.0.7 on 2024-08-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0004_alter_cliente_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
    ]
