# Generated by Django 5.0.7 on 2024-08-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0007_remove_cliente_telefone_cliente_inicio_de_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='inicio_de_contrato',
            field=models.DateField(),
        ),
    ]
