# Generated by Django 5.0.7 on 2024-08-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0010_clientes_status_clientes_termino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='equipamento',
            field=models.CharField(choices=[('Isaca', 'Isca'), ('Rastreador', 'Rastreador'), ('Tets', 'Tets')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='quabtidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
