# Generated by Django 5.0.7 on 2024-08-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0011_clientes_equipamento_clientes_quabtidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='quabtidade',
            new_name='quantidade',
        ),
    ]
