# Generated by Django 5.0.7 on 2024-08-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_final', models.DateTimeField(blank=True, null=True)),
                ('prestador', models.CharField(choices=[('Sombra armado', 'Sombra armado')], max_length=50)),
                ('agente', models.CharField(max_length=255)),
                ('placa', models.CharField(max_length=255)),
                ('id_equipamento', models.CharField(max_length=255)),
                ('km_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('km_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pedagio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
