# Generated by Django 5.1.1 on 2024-09-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(blank=True, max_length=255, null=True)),
                ('placa', models.CharField(blank=True, max_length=255, null=True)),
                ('origen', models.CharField(blank=True, max_length=255, null=True)),
                ('destino', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
