# Generated by Django 5.1.1 on 2024-09-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0003_rename_destino_agentes_franquia_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacompanhamento',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacompanhamento.agentes'),
        ),
    ]
