# Generated by Django 5.0.7 on 2024-08-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_options_remove_produto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='valorc',
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
