# Generated by Django 5.0.7 on 2024-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_produto_valorc_alter_produto_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
