# Generated by Django 5.1.1 on 2024-09-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_produto_descricao_remove_produto_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
