# Generated by Django 5.0.7 on 2024-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regcliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('franquia_km', models.TextField(blank=True, max_length=50, null=True)),
                ('franquiah', models.TimeField()),
                ('valor_acionamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valorkm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_exedente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
