# Generated by Django 5.1.1 on 2024-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regcliente', '0002_alter_regcliente_valor_acionamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regcliente',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
