# Generated by Django 5.0.7 on 2024-08-28 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acompanhamento', '0012_rename_quabtidade_clientes_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='reativacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_reativacao', models.CharField(blank=True, max_length=50, null=True)),
                ('canal_solicitacao', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.CharField(max_length=100)),
                ('id_equipamentos', models.CharField(blank=True, default='', max_length=300)),
                ('ccid_equipamentos', models.CharField(blank=True, default='', max_length=300)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reativacao_nome', to='acompanhamento.clientes')),
            ],
        ),
    ]
