# Generated by Django 5.0.7 on 2024-09-12 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reativacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_reativacao', models.CharField(blank=True, max_length=50, null=True)),
                ('canal_solicitacao', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.CharField(max_length=100)),
                ('status_reativacao', models.CharField(choices=[('', 'Selecione o Status'), ('Vazio', 'Vazio'), ('faturado', 'Faturado')], default='', max_length=10)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reativacao_nome', to='acompanhamento.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='IdIccid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipamentos', models.CharField(blank=True, default='', max_length=300)),
                ('ccid_equipamentos', models.CharField(blank=True, default='', max_length=300)),
                ('reativacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_iccids', to='reativacao.reativacao')),
            ],
        ),
    ]
