# Generated by Django 5.0.7 on 2024-08-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reativacao',
            name='ccid_equipamentos',
        ),
        migrations.RemoveField(
            model_name='reativacao',
            name='id_equipamentos',
        ),
        migrations.CreateModel(
            name='IdIccid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipamentos', models.CharField(blank=True, default='', max_length=300)),
                ('ccid_equipamentos', models.CharField(blank=True, default='', max_length=300)),
                ('reativacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_iccids', to='reativacao.reativacao')),
            ],
        ),
    ]
