# Generated by Django 5.0.7 on 2024-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0002_remove_reativacao_ccid_equipamentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reativacao',
            name='status_reativacao',
            field=models.CharField(choices=[('', 'Vazio'), ('faturado', 'Faturado')], default='', max_length=10),
        ),
    ]
