# Generated by Django 5.0.7 on 2024-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0003_reativacao_status_reativacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reativacao',
            name='status_reativacao',
            field=models.CharField(choices=[('', 'Selecione o Status'), ('Vazio', 'Vazio'), ('faturado', 'Faturado')], default='', max_length=10),
        ),
    ]
