# Generated by Django 5.1.1 on 2024-09-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rprestador',
            name='valor_acionamento',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rprestador',
            name='valor_exedente',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rprestador',
            name='valorkm',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
